//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD2_Presence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TD2_Presence.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby zmienić ustawienia naciśnij Enter, aby wyjść dowolny inny klawisz.
        /// </summary>
        internal static string Change_Settings_Info {
            get {
                return ResourceManager.GetString("Change Settings Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaleziono dyżurnego! Dane będą odświeżać się co {0}s!.
        /// </summary>
        internal static string Dispatcher_Found_Info {
            get {
                return ResourceManager.GetString("Dispatcher Found Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono dyżurnego online! Oczekiwanie....
        /// </summary>
        internal static string Dispatcher_Not_Found_Info {
            get {
                return ResourceManager.GetString("Dispatcher Not Found Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaleziono maszynistę! Dane będą odświeżać się co {0}s!.
        /// </summary>
        internal static string Driver_Found_Info {
            get {
                return ResourceManager.GetString("Driver Found Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono maszynisty online! Oczekiwanie....
        /// </summary>
        internal static string Driver_Not_Found_Info {
            get {
                return ResourceManager.GetString("Driver Not Found Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz poprawny nick!.
        /// </summary>
        internal static string Incorrect_Username_Warning {
            get {
                return ResourceManager.GetString("Incorrect Username Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upewnij się, że masz włączoną oryginalną desktopową aplikację Discorda, a następnie wpisz dane poniżej. Aktywność zniknie automatycznie po zamknięciu tego okna terminalu. Miłego korzystania!.
        /// </summary>
        internal static string Initial_Info_1 {
            get {
                return ResourceManager.GetString("Initial Info 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamiętaj, aby włączyć wyświetlanie statusu rozgrywki w ustawieniach aktywności Discorda ORAZ indywidualnych ustawieniach prywatności serwera, na którym chcesz je pokazać!.
        /// </summary>
        internal static string Initial_Info_2 {
            get {
                return ResourceManager.GetString("Initial Info 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz tryb (1 - dyżurny; 2 - maszynista; 3 - edytor; 4 - język; inne - wyjście): .
        /// </summary>
        internal static string Mode_Choice_Info {
            get {
                return ResourceManager.GetString("Mode Choice Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Presence gotowy!.
        /// </summary>
        internal static string Presence_Loaded_Info {
            get {
                return ResourceManager.GetString("Presence Loaded Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łączenie z Discordem....
        /// </summary>
        internal static string Presence_Loading_Info {
            get {
                return ResourceManager.GetString("Presence Loading Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semafor.
        /// </summary>
        internal static string RPC_Current_Signal_Title {
            get {
                return ResourceManager.GetString("RPC Current Signal Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szlak.
        /// </summary>
        internal static string RPC_Current_Track_Title {
            get {
                return ResourceManager.GetString("RPC Current Track Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb dyżurnego.
        /// </summary>
        internal static string RPC_Dispatcher_Mode_Title {
            get {
                return ResourceManager.GetString("RPC Dispatcher Mode Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyżurny na scenerii.
        /// </summary>
        internal static string RPC_Dispatcher_Scenery_Title {
            get {
                return ResourceManager.GetString("RPC Dispatcher Scenery Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb maszynisty.
        /// </summary>
        internal static string RPC_Driver_Mode_Title {
            get {
                return ResourceManager.GetString("RPC Driver Mode Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brak rozkładu jazdy.
        /// </summary>
        internal static string RPC_Driver_No_Timetable_Title {
            get {
                return ResourceManager.GetString("RPC Driver No Timetable Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły rozkładu jazdy.
        /// </summary>
        internal static string RPC_Driver_Timetable_Button_Label {
            get {
                return ResourceManager.GetString("RPC Driver Timetable Button Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W edytorze scenerii.
        /// </summary>
        internal static string RPC_Scenery_Details_Info {
            get {
                return ResourceManager.GetString("RPC Scenery Details Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuje scenerię: .
        /// </summary>
        internal static string RPC_Scenery_State_Info {
            get {
                return ResourceManager.GetString("RPC Scenery State Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetlanie statusu edycji scenerii {0}!.
        /// </summary>
        internal static string Scenery_Editing_Info {
            get {
                return ResourceManager.GetString("Scenery Editing Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwę scenerii: .
        /// </summary>
        internal static string Scenery_Name_Prompt {
            get {
                return ResourceManager.GetString("Scenery Name Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szukanie informacji o graczu {0}....
        /// </summary>
        internal static string Searching_User_Info {
            get {
                return ResourceManager.GetString("Searching User Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas próby połączenia z serwerem!.
        /// </summary>
        internal static string Server_Error_Warning {
            get {
                return ResourceManager.GetString("Server Error Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIEDOSTĘPNY.
        /// </summary>
        internal static string Status_Code__1 {
            get {
                return ResourceManager.GetString("Status Code -1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIEWPISANY.
        /// </summary>
        internal static string Status_Code__2 {
            get {
                return ResourceManager.GetString("Status Code -2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEZ LIMITU.
        /// </summary>
        internal static string Status_Code_0 {
            get {
                return ResourceManager.GetString("Status Code 0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZARAZ WRACAM.
        /// </summary>
        internal static string Status_Code_1 {
            get {
                return ResourceManager.GetString("Status Code 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOŃCZY.
        /// </summary>
        internal static string Status_Code_2 {
            get {
                return ResourceManager.GetString("Status Code 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRAK MIEJSCA.
        /// </summary>
        internal static string Status_Code_3 {
            get {
                return ResourceManager.GetString("Status Code 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIEZNANY.
        /// </summary>
        internal static string Status_Code_4 {
            get {
                return ResourceManager.GetString("Status Code 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOSTĘPNY DO.
        /// </summary>
        internal static string Status_Code_Available {
            get {
                return ResourceManager.GetString("Status Code Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD2 Presence.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdzanie aktualizacji....
        /// </summary>
        internal static string Update_Checking {
            get {
                return ResourceManager.GetString("Update Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowa wersja aplikacji ({0}) jest dostępna! Czy chcesz ją teraz pobrać?.
        /// </summary>
        internal static string Update_Dialog_Desc {
            get {
                return ResourceManager.GetString("Update Dialog Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępna nowa wersja.
        /// </summary>
        internal static string Update_Dialog_Title {
            get {
                return ResourceManager.GetString("Update Dialog Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! Nie można pobrać aktualizacji! Spróbuj ponownie, a jeśli problem nadal występuje zgłoś go do autora!.
        /// </summary>
        internal static string Update_Error {
            get {
                return ResourceManager.GetString("Update Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W tym momencie twoja domyślna przeglądarka powinna pobrać paczkę ZIP z najnowszą wersją aplikacji..
        /// </summary>
        internal static string Update_Info_1 {
            get {
                return ResourceManager.GetString("Update Info 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeśli nic się nie otworzyło, skopiuj i otwórz ręcznie poniższy link, a następnie wypakuj zawartość w dowolnym miejscu..
        /// </summary>
        internal static string Update_Info_2 {
            get {
                return ResourceManager.GetString("Update Info 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naciśnij jakikolwiek przycisk, aby zamknąć aplikację!.
        /// </summary>
        internal static string Update_Info_3 {
            get {
                return ResourceManager.GetString("Update Info 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten użytkownik jest zablokowany!.
        /// </summary>
        internal static string User_Is_Blocked_Warning {
            get {
                return ResourceManager.GetString("User Is Blocked Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwę użytkownika: .
        /// </summary>
        internal static string Username_Prompt {
            get {
                return ResourceManager.GetString("Username Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwę użytkownika (domyślnie: {0}): .
        /// </summary>
        internal static string Username_Prompt_With_Default {
            get {
                return ResourceManager.GetString("Username Prompt With Default", resourceCulture);
            }
        }
    }
}
